/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecadesRouteImport } from './routes/decades'
import { Route as DirectorsRouteImport } from './routes/directors'
import { Route as DecadesDecadeRouteImport } from './routes/decades_.$decade'
import { Route as FilmsSlugRouteImport } from './routes/films.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecadesRoute = DecadesRouteImport.update({
  id: '/decades',
  path: '/decades',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorsRoute = DirectorsRouteImport.update({
  id: '/directors',
  path: '/directors',
  getParentRoute: () => rootRouteImport,
} as any)
const DecadesDecadeRoute = DecadesDecadeRouteImport.update({
  id: '/decades_/$decade',
  path: '/decades/$decade',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsSlugRoute = FilmsSlugRouteImport.update({
  id: '/films/$slug',
  path: '/films/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decades': typeof DecadesRoute
  '/directors': typeof DirectorsRoute
  '/decades/$decade': typeof DecadesDecadeRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decades': typeof DecadesRoute
  '/directors': typeof DirectorsRoute
  '/decades/$decade': typeof DecadesDecadeRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decades': typeof DecadesRoute
  '/directors': typeof DirectorsRoute
  '/decades_/$decade': typeof DecadesDecadeRoute
  '/films/$slug': typeof FilmsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/decades' | '/directors' | '/decades/$decade' | '/films/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decades' | '/directors' | '/decades/$decade' | '/films/$slug'
  id:
    | '__root__'
    | '/'
    | '/decades'
    | '/directors'
    | '/decades_/$decade'
    | '/films/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecadesRoute: typeof DecadesRoute
  DirectorsRoute: typeof DirectorsRoute
  DecadesDecadeRoute: typeof DecadesDecadeRoute
  FilmsSlugRoute: typeof FilmsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decades': {
      id: '/decades'
      path: '/decades'
      fullPath: '/decades'
      preLoaderRoute: typeof DecadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directors': {
      id: '/directors'
      path: '/directors'
      fullPath: '/directors'
      preLoaderRoute: typeof DirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decades_/$decade': {
      id: '/decades_/$decade'
      path: '/decades/$decade'
      fullPath: '/decades/$decade'
      preLoaderRoute: typeof DecadesDecadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$slug': {
      id: '/films/$slug'
      path: '/films/$slug'
      fullPath: '/films/$slug'
      preLoaderRoute: typeof FilmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecadesRoute: DecadesRoute,
  DirectorsRoute: DirectorsRoute,
  DecadesDecadeRoute: DecadesDecadeRoute,
  FilmsSlugRoute: FilmsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
