/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecadesRouteImport } from './routes/decades'
import { Route as DecadesDecadeRouteImport } from './routes/decades_.$decade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecadesRoute = DecadesRouteImport.update({
  id: '/decades',
  path: '/decades',
  getParentRoute: () => rootRouteImport,
} as any)
const DecadesDecadeRoute = DecadesDecadeRouteImport.update({
  id: '/decades_/$decade',
  path: '/decades/$decade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decades': typeof DecadesRoute
  '/decades/$decade': typeof DecadesDecadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decades': typeof DecadesRoute
  '/decades/$decade': typeof DecadesDecadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decades': typeof DecadesRoute
  '/decades_/$decade': typeof DecadesDecadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decades' | '/decades/$decade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decades' | '/decades/$decade'
  id: '__root__' | '/' | '/decades' | '/decades_/$decade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecadesRoute: typeof DecadesRoute
  DecadesDecadeRoute: typeof DecadesDecadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decades': {
      id: '/decades'
      path: '/decades'
      fullPath: '/decades'
      preLoaderRoute: typeof DecadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decades_/$decade': {
      id: '/decades_/$decade'
      path: '/decades/$decade'
      fullPath: '/decades/$decade'
      preLoaderRoute: typeof DecadesDecadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecadesRoute: DecadesRoute,
  DecadesDecadeRoute: DecadesDecadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
